In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("customer_churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
#EDA
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
#Get the nulls and duplicates if any
df.isnull().sum().sum()

np.int64(0)

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['TotalCharges'].value_counts()

TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

In [8]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors = 'coerce')

In [9]:
df['TotalCharges'].value_counts()

TotalCharges
20.20      11
19.75       9
20.05       8
19.90       8
19.65       8
           ..
6849.40     1
692.35      1
130.15      1
3211.90     1
6844.50     1
Name: count, Length: 6530, dtype: int64

In [10]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [11]:
df['TotalCharges'] = df['TotalCharges'].fillna(df['tenure']*df['MonthlyCharges'])

In [14]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [17]:
df.drop(columns = ['customerID'], inplace = True)

In [16]:
#Update categorical values to Numerical
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [18]:
mapping = {}
for i in df.columns:
    if df[i].dtype == 'object':
        df[i] = le.fit_transform(df[i])
        mapping[i] = dict(zip(le.classes_,le.transform(le.classes_)))
print(mapping)

{'gender': {'Female': np.int64(0), 'Male': np.int64(1)}, 'Partner': {'No': np.int64(0), 'Yes': np.int64(1)}, 'Dependents': {'No': np.int64(0), 'Yes': np.int64(1)}, 'PhoneService': {'No': np.int64(0), 'Yes': np.int64(1)}, 'MultipleLines': {'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}, 'InternetService': {'DSL': np.int64(0), 'Fiber optic': np.int64(1), 'No': np.int64(2)}, 'OnlineSecurity': {'No': np.int64(0), 'No internet service': np.int64(1), 'Yes': np.int64(2)}, 'OnlineBackup': {'No': np.int64(0), 'No internet service': np.int64(1), 'Yes': np.int64(2)}, 'DeviceProtection': {'No': np.int64(0), 'No internet service': np.int64(1), 'Yes': np.int64(2)}, 'TechSupport': {'No': np.int64(0), 'No internet service': np.int64(1), 'Yes': np.int64(2)}, 'StreamingTV': {'No': np.int64(0), 'No internet service': np.int64(1), 'Yes': np.int64(2)}, 'StreamingMovies': {'No': np.int64(0), 'No internet service': np.int64(1), 'Yes': np.int64(2)}, 'Contract': {'Month-to-month': np.int64(0), 'One year': np.int64(1), 'Two year': np.int64(2)}, 'PaperlessBilling': {'No': np.int64(0), 'Yes': np.int64(1)}, 'PaymentMethod': {'Bank transfer (automatic)': np.int64(0), 'Credit card (automatic)': np.int64(1), 'Electronic check': np.int64(2), 'Mailed check': np.int64(3)}, 'Churn': {'No': np.int64(0), 'Yes': np.int64(1)}}

In [19]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1990.50,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,7362.90,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,346.45,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,6844.50,0

In [21]:
#Get the value counts for the churn
df['Churn'].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [24]:
#Train test split
x = df.drop("Churn",axis = 1)
y = df['Churn']

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20,random_state = 42)

In [26]:
x_train

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
2142,0,0,0,1,21,1,0,0,2,0,2,0,0,2,1,0,3,64.85,1336.80
1623,0,0,0,0,54,1,2,1,0,2,0,0,2,2,2,1,0,97.20,5129.45
6074,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,2,23.45,23.45
1362,1,0,0,0,4,1,0,1,0,0,0,0,0,0,0,1,2,70.20,237.95
6754,1,0,0,1,0,1,2,0,2,2,0,2,0,0,2,1,0,61.90,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,1,0,1,0,1,1,0,1,2,0,0,0,2,2,0,1,2,95.00,95.00
5191,0,0,1,1,23,1,2,0,2,2,2,2,2,2,2,1,1,91.10,2198.30
5226,1,0,1,1,12,1,0,2,1,1,1,1,1,1,0,1,2,21.15,306.05
5390,1,1,0,0,12,1,2,1,0,0,2,0,2,2,0,1,2,99.45,1200.15
860,1,0,0,0,26,1,0,2,1,1,1,1,1,1,1,0,1,19.80,457.30

In [27]:
x_test

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
185,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,2,24.80,24.80
2715,1,0,0,0,41,1,2,2,1,1,1,1,1,1,0,1,0,25.25,996.45
3825,0,0,1,1,52,1,0,2,1,1,1,1,1,1,2,0,3,19.35,1031.70
1807,0,0,0,0,1,1,0,1,0,0,2,0,0,0,0,0,2,76.35,76.35
132,1,0,0,0,67,1,0,0,0,0,0,2,0,0,2,0,0,50.55,3260.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6366,0,0,1,0,64,1,0,0,0,2,2,2,0,2,2,1,3,68.30,4378.80
315,1,0,1,1,51,1,2,1,2,2,0,2,2,2,1,0,1,110.05,5686.40
2439,1,0,1,1,17,1,0,2,1,1,1,1,1,1,1,0,0,19.90,329.75
5002,0,0,1,1,69,0,1,0,2,0,2,0,0,2,2,1,1,43.95,2960.10
1161,1,0,0,1,1,0,1,0,0,2,0,0,0,0,0,1,3,31.35,31.35

In [28]:
y_train

2142    0
1623    0
6074    1
1362    1
6754    0
       ..
3772    1
5191    0
5226    0
5390    1
860     0
Name: Churn, Length: 5634, dtype: int64

In [29]:
y_test

185     1
2715    0
3825    0
1807    1
132     0
       ..
6366    0
315     0
2439    0
5002    0
1161    1
Name: Churn, Length: 1409, dtype: int64

In [30]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [31]:
from sklearn.feature_selection import RFE
#Apply rfe
rfe=RFE(model)
rfe.fit(x,y)

C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

RFE(estimator=LogisticRegression())

In [32]:
#RFE will give the index of the columns that are important
rfe.support_  #support_ will give you a boolean list in which wherever you are having True means that column is imp

array([False,  True, False,  True, False,  True,  True, False,  True,
        True, False,  True, False, False,  True,  True, False, False,
       False])

In [33]:
imp_index_col=[i for i,data in enumerate(rfe.support_) if data==True]

In [34]:
column_name=x.columns
imp_cols=[column_name[i] for i in imp_index_col]
imp_cols

['SeniorCitizen',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'OnlineSecurity',
 'OnlineBackup',
 'TechSupport',
 'Contract',
 'PaperlessBilling']

In [35]:
#test the model
model.fit(x_train,y_train)
#predict to test the model. Test the model
y_pred = model.predict(x_test)
y_pred

C:\Users\Shreyas_Srijith\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([1, 0, 0, ..., 0, 0, 1], shape=(1409,))

In [36]:
#Evaluate the Model
#For a Binary Classification Problem:

 #Accuracy Score - (TP+TN)/(TP+TN+FP+FN) - TP: True Positive, TN: True Negative, FP: False Positive, FN: False negative
 #Precision Score - Out of all positives, how many were actually positive TP/(TP+FP)
 #Recall Score- Out of all positives, how many were actually predicted by the model TP/(TP+FN)
 #Confusion Matrix

from sklearn.metrics import *

In [37]:
cm = confusion_matrix(y_test,y_pred) #output format [[TN,FP],[FN,TP]]

In [38]:
cm

array([[922, 114],
       [155, 218]])

In [39]:
accuracy_score(y_test,y_pred)

0.8090844570617459

In [40]:
precision_score(y_test,y_pred)

0.6566265060240963

In [41]:
recall_score(y_test,y_pred)

0.5844504021447721

In [42]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [43]:
#test the model
y_pred = dt_model.predict(x_test)
y_pred

array([1, 0, 0, ..., 0, 0, 1], shape=(1409,))

In [44]:
#Evaluating the model
from sklearn.metrics import *

In [45]:
accuracy_score(y_test,y_pred)

0.730305180979418

In [46]:
precision_score(y_test,y_pred)

0.4908616187989556

In [47]:
recall_score(y_test,y_pred)

0.5040214477211796

In [58]:
# Hyperparameter tuning
tree_model = DecisionTreeClassifier()

In [59]:
#best hyper-parameter
#Grid Search CV

In [66]:
param_grid = {
    "criterion" : ["gini","entropy"],
    "max_depth" : [3,4,6,8,9,10],
    "min_samples_split" : [2,5,10],
    "min_samples_leaf" : [1,2,4]
}

In [67]:
from sklearn.model_selection import GridSearchCV

In [68]:
grid_search = GridSearchCV(
    estimator = tree_model,
    param_grid = param_grid,
    cv = 5, #cross validation - data will be split into 5 parts (cv = 4 or 5 is sufficient)
    scoring = "accuracy"
)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 6, 8, 9, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]},
             scoring='accuracy')

In [70]:
#best hyperparameter
print("Best Hyperparameter:",grid_search.best_params_)

Best Hyperparameter: {'criterion': 'entropy', 'max_depth': 6, 'min_samples_leaf': 2, 'min_samples_split': 2}

In [71]:
#best score
print("Best Score:",grid_search.best_score_)

Best Score: 0.7854088488434219

In [72]:
dt_model = DecisionTreeClassifier(criterion= 'entropy', max_depth= 6, min_samples_leaf= 2, min_samples_split= 2)

In [73]:
dt_model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_leaf=2)

In [74]:
ypred = dt_model.predict(x_test)

In [75]:
accuracy_score(y_test,ypred)

0.8005677785663591

In [76]:
#Getting ready for RandomForest
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=42)

In [77]:
x_train_sm,y_train_sm=sm.fit_resample(x_train,y_train)

In [78]:
x_train_sm

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,0,1,21,1,0,0,2,0,2,0,0,2,1,0,3,64.850000,1336.800000
1,0,0,0,0,54,1,2,1,0,2,0,0,2,2,2,1,0,97.200000,5129.450000
2,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,2,23.450000,23.450000
3,1,0,0,0,4,1,0,1,0,0,0,0,0,0,0,1,2,70.200000,237.950000
4,1,0,0,1,0,1,2,0,2,2,0,2,0,0,2,1,0,61.900000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8271,0,0,0,0,5,1,0,1,0,0,0,0,2,1,0,1,1,88.121375,451.834304
8272,0,0,0,0,44,1,0,1,0,0,1,0,0,2,0,1,1,90.725171,4048.457431
8273,0,0,0,0,35,1,2,1,0,1,1,0,2,1,0,1,2,101.603909,3547.522160
8274,0,0,0,0,44,0,0,1,0,0,0,1,0,0,0,0,1,20.891535,933.033556
8275,1,0,1,0,26,1,2,1,0,0,0,0,0,0,0,1,2,76.757348,1891.297782

In [79]:
y_train_sm

0       0
1       0
2       1
3       1
4       0
       ..
8271    1
8272    1
8273    1
8274    1
8275    1
Name: Churn, Length: 8276, dtype: int64

In [80]:
print("Before SMOTE")
print(y_train)
print("After SMOTE")
print(y_train_sm)

Before SMOTE
2142    0
1623    0
6074    1
1362    1
6754    0
       ..
3772    1
5191    0
5226    0
5390    1
860     0
Name: Churn, Length: 5634, dtype: int64
After SMOTE
0       0
1       0
2       1
3       1
4       0
       ..
8271    1
8272    1
8273    1
8274    1
8275    1
Name: Churn, Length: 8276, dtype: int64

In [84]:
#Train the model
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier()
param_grid = {
    "n_estimators" : [100,150,200],
    "criterion" : ["gini","entropy"],
    "max_depth" : [3,4,6,8,9,10],
    "min_samples_split" : [2,5,10],
    "min_samples_leaf" : [1,2,4],
    "random_state" : [0,42]
}
grid_search = GridSearchCV(
    estimator = rf_model,
    param_grid = param_grid,
    cv = 5, #cross validation - data will be split into 5 parts (cv = 4 or 5 is sufficient)
    scoring = "accuracy"
)

grid_search.fit(x_train_sm,y_train_sm)

KeyboardInterrupt:

In [ ]:
rf_model.predict()