In [7]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Country 1.csv")
df

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34.0,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,9.0,89,41.6,~0.0/1.6,-99,26,-99,-99,-99,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,-99,-99,-99.0,-99,...,-99,49,2.7,-99,-99,-99,-99,-99,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,25.1,298,1.0,22.7/0.9,668,12,72.0/46.5,92.5/34.1,2.99,-99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,21.0,88,65.6,4.5/0.3,374,26,85.6/51.3,55.6/35.7,3.96,-99
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893,1.1,890.4,13.0,...,16.4,89,37.2,12.0/0.8,482,30,97.0/67.3,49.3/30.8,6.00,-99

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 50 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   country                                                     229 non-null    object
 1   Region                                                      229 non-null    object
 2   Surface area (km2)                                          229 non-null    object
 3   Population in thousands (2017)                              229 non-null    int64
 4   Population density (per km2, 2017)                          229 non-null    float64
 5   Sex ratio (m per 100 f, 2017)                               229 non-null    float64
 6   GDP: Gross domestic product (million current US$)           229 non-null    int64
 7   GDP growth rate (annual %, const. 2005 prices)              229 non-null    object
 8   GDP per capita (current US$)                                229 non-null    float64
 9   Economy: Agriculture (% of GVA)                             229 non-null    object
 10  Economy: Industry (% of GVA)                                229 non-null    float64
 11  Economy: Services and other activity (% of GVA)             229 non-null    float64
 12  Employment: Agriculture (% of employed)                     229 non-null    object
 13  Employment: Industry (% of employed)                        229 non-null    object
 14  Employment: Services (% of employed)                        229 non-null    object
 15  Unemployment (% of labour force)                            229 non-null    object
 16  Labour force participation (female/male pop. %)             229 non-null    object
 17  Agricultural production index (2004-2006=100)               229 non-null    int64
 18  Food production index (2004-2006=100)                       229 non-null    int64
 19  International trade: Exports (million US$)                  229 non-null    object
 20  International trade: Imports (million US$)                  229 non-null    object
 21  International trade: Balance (million US$)                  229 non-null    object
 22  Balance of payments, current account (million US$)          229 non-null    object
 23  Population growth rate (average annual %)                   229 non-null    object
 24  Urban population (% of total population)                    229 non-null    float64
 25  Urban population growth rate (average annual %)             229 non-null    object
 26  Fertility rate, total (live births per woman)               229 non-null    object
 27  Life expectancy at birth (females/males, years)             229 non-null    object
 28  Population age distribution (0-14 / 60+ years, %)           229 non-null    object
 29  International migrant stock (000/% of total pop.)           229 non-null    object
 30  Refugees and others of concern to UNHCR (in thousands)      229 non-null    object
 31  Infant mortality rate (per 1000 live births                 229 non-null    object
 32  Health: Total expenditure (% of GDP)                        229 non-null    float64
 33  Health: Physicians (per 1000 pop.)                          229 non-null    object
 34  Education: Government expenditure (% of GDP)                229 non-null    object
 35  Education: Primary gross enrol. ratio (f/m per 100 pop.)    229 non-null    object
 36  Education: Secondary gross enrol. ratio (f/m per 100 pop.)  229 non-null    object
 37  Education: Tertiary gross enrol. ratio (f/m per 100 pop.)   229 non-null    object
 38  Seats held by women in national parliaments %               229 non-null    float64
 39  Mobile-cellular subscriptions (per 100 inhabitants)         229 non-null    object
 40  Mobile-cellular subscriptions (per 100 inhabitants).1       229 non-null    object
 41  Individuals using the Internet (per 100 inhabitants)        229 non-null    int64
 42  Threatened species (number)                                 229 non-null    object
 43  Forested area (% of land area)                              229 non-null    object
 44  CO2 emission estimates (million tons/tons per capita)       229 non-null    int64
 45  Energy production, primary (Petajoules)                     229 non-null    int64
 46  Energy supply per capita (Gigajoules)                       229 non-null    object
 47  Pop. using improved drinking water (urban/rural, %)         229 non-null    object
 48  Pop. using improved sanitation facilities (urban/rural, %)  229 non-null    object
 49  Net Official Development Assist. received (% of GNI)        229 non-null    int64
dtypes: float64(8), int64(8), object(34)
memory usage: 89.6+ KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
#1. Find the average population of all the countries in the data 2017
avg_population = df["Population in thousands (2017)"].mean()
avg_population

np.float64(32756.794759825327)

In [8]:
df.describe()

,Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),GDP per capita (current US$),Economy: Industry (% of GVA),Economy: Services and other activity (% of GVA),Agricultural production index (2004-2006=100),Food production index (2004-2006=100),Urban population (% of total population),Health: Total expenditure (% of GDP),Seats held by women in national parliaments %,Individuals using the Internet (per 100 inhabitants),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Net Official Development Assist. received (% of GNI)
count,2.290000e+02,229.000000,229.000000,2.290000e+02,229.000000,229.000000,229.000000,229.000000,229.000000,229.000000,229.000000,229.000000,229.000000,229.000000,229.000000,229.0
mean,3.275679e+04,462.824891,100.202183,3.214339e+05,14251.877729,15.958952,46.408734,99.270742,100.043668,59.508734,-11.248908,1.861572,198.711790,2464.262009,80.847162,-99.0
std,1.332751e+05,2305.384253,28.327837,1.478690e+06,23391.266933,38.684631,48.603730,62.787137,63.198988,25.206404,39.924937,45.674635,296.453089,9912.891745,121.808263,0.0
min,1.000000e+00,0.100000,-99.000000,-9.900000e+01,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,0.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.0
25%,4.310000e+02,35.900000,96.400000,2.078000e+03,1207.900000,15.400000,47.300000,98.000000,98.000000,39.800000,3.400000,7.200000,55.000000,2.000000,19.000000,-99.0
50%,5.448000e+03,88.100000,99.000000,1.625100e+04,4836.100000,25.500000,59.500000,111.000000,112.000000,59.900000,5.600000,17.100000,97.000000,108.000000,47.000000,-99.0
75%,1.919300e+04,222.800000,101.700000,1.179550e+05,16344.100000,32.800000,70.700000,130.000000,130.000000,79.600000,7.800000,27.100000,196.000000,961.000000,103.000000,-99.0
max,1.409517e+06,25969.800000,301.200000,1.803665e+07,169491.800000,79.900000,94.000000,199.000000,199.000000,100.000000,17.100000,61.300000,2358.000000,101394.000000,952.000000,-99.0

In [9]:
#2.Find the most common region in which the countries are present
import statistics as stats
stats.mode(df['Region'])

'Caribbean'

In [11]:
df['Region'].mode()

0    Caribbean
Name: Region, dtype: object

In [10]:
df['Region'].value_counts().head()

Region
Caribbean         25
EasternAfrica     19
WesternAsia       18
SouthernEurope    16
WesternAfrica     16
Name: count, dtype: int64

In [13]:
#3.Find the range of population of all countries in 2017
pop_range = df['Population in thousands (2017)'].max() - df['Population in thousands (2017)'].min()
pop_range

1409516

In [15]:
#4. Find the inter quartile range of the population of all countries in 2017
pop_q1 = np.percentile(df['Population in thousands (2017)'],25)
pop_q3 = np.percentile(df['Population in thousands (2017)'],75)
iqr = pop_q3 - pop_q1
iqr

np.float64(18762.0)

In [18]:
# from the entire dataset create a sample of 50 rows
sample_df = df.sample(50,random_state = 7)
sample_df

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
222,Venezuela (Bolivarian Republic of),SouthAmerica,912050,31977,36.3,99.0,344331,-6.2,11068.9,5.3,...,61.9,328,53.1,185.2/6.1,7460,90,95.0/77.9,97.5/69.9,0.01,-99
186,Solomon Islands,Melanesia,28896,611,21.8,103.4,1075,3.2,1841.6,28.2,...,10.0,245,78.3,0.2/0.4,3,11,93.2/77.2,81.4/15.0,16.47,-99
66,Estonia,NorthernEurope,45227,1310,30.9,88.2,22460,1.4,17112.0,3.4,...,88.4,23,52.7,19.5/14.8,242,193,100.0/99.0,97.5/96.6,-99,-99
22,Bermuda,NorthernAmerica,53,61,1227.0,91.4,5853,0.4,94399.9,0.7,...,98.3,72,20.0,0.6/9.2,1,136,-99,-99,-99,-99
80,Gibraltar,SouthernEurope,6,35,3457.1,101.8,-99,-99,-99.0,-99,...,65.0,31,0.0,0.5/16.5,-99,259,-99,-99,-99,-99
154,Palau,Micronesia,459,22,47.2,113.3,258,5.7,12122.5,3.8,...,-99,182,87.6,0.3/12.4,-99,172,97.0/86.0,100.0/100.0,5.05,-99
168,Rwanda,EasternAfrica,26338,12208,494.9,96.2,8096,6.9,697.3,34.6,...,18.0,62,19.2,0.8/0.1,84,8,86.6/71.9,58.5/62.9,13.67,-99
101,Israel,WesternAsia,22072,8322,384.5,98.7,299413,2.5,37129.4,1.3,...,78.9,174,7.5,64.6/8.1,313,119,100.0/100.0,100.0/100.0,-99,-99
24,Bolivia (Plurinational State of),SouthAmerica,1098581,11052,10.2,100.2,32998,4.8,3076.8,12.6,...,45.1,231,50.8,20.4/1.9,962,32,96.7/75.6,60.8/27.5,2.38,-99
114,Lesotho,SouthernAfrica,30355,2233,73.6,94.4,2008,2.8,940.6,7.7,...,16.1,18,1.6,2.5/1.2,31,28,94.6/77.0,37.3/27.6,4.11,-99
11,Australia,Oceania,7692060,24451,3.2,99.3,1230859,2.4,51352.2,2.5,...,84.6,948,16.2,361.3/15.3,15282,222,100.0/100.0,100.0/100.0,-99,-99
74,French Polynesia,Polynesia,4000,283,77.3,103.7,5135,1.6,18161.0,2.8,...,64.6,175,42.3,0.8/2.9,1,43,100.0/100.0,98.5/98.5,-99,-99
140,Namibia,SouthernAfrica,824116,2534,3.1,94.7,11491,5.3,4673.6,6.6,...,22.3,115,8.5,3.8/1.6,19,31,98.2/84.6,54.5/16.8,1.24,-99
94,Iceland,NorthernEurope,103000,335,3.3,100.7,16780,4.2,50936.0,6.4,...,98.2,27,0.5,2.0/6.1,284,952,100.0/100.0,98.7/100.0,-99,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
143,Netherlands,WesternEurope,41542,17036,505.2,99.0,750318,2.0,44332.1,1.8,...,93.1,40,11.1,167.3/9.9,2447,178,100.0/100.0,97.5/99.9,-99,-99
180,Seychelles,EasternAfrica,457,95,206.0,97.2,1363,6.8,14133.2,2.7,...,58.1,439,88.4,0.5/5.2,0,72,95.7/95.7,98.4/98.4,0.50,-99
113,Lebanon,WesternAsia,10452,6082,594.6,100.6,50149,1.5,8571.4,3.2,...,74.0,87,13.4,24.1/4.3,7,55,99.0/99.0,80.7/80.7,2.04,-99
60,Dominican Republic,Caribbean,48671,10767,222.8,99.2,67103,7.0,6373.6,6.6,...,51.9,184,40.4,21.5/2.1,28,28,85.4/81.9,86.2/75.7,0.43,-99
133,Monaco,WesternEurope,2,39,25969.8,94.7,6258,5.4,165870.6,-99,...,93.4,21,-99,-99,-99,-99,100.0/...,100.0/...,-99,-99
193,Sudan,NorthernAfrica,-99,40533,23.0,99.9,79546,4.9,1977.0,32.4,...,26.6,133,-99,15.4/0.4,682,16,-99,-99,1.09,-99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,21.0,88,65.6,4.5/0.3,374,26,85.6/51.3,55.6/35.7,3.96,-99
128,Mauritania,WesternAfrica,1030700,4420,4.3,101.6,5023,1.2,1235.0,20.9,...,15.2,86,0.2,2.7/0.7,31,13,58.4/57.1,57.5/13.8,5.02,-99
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,9.0,89,41.6,~0.0/1.6,-99,26,-99,-99,-99,-99
121,Malawi,EasternAfrica,118484,18622,197.5,98.2,6420,3.0,372.9,26.1,...,9.3,176,33.6,1.3/0.1,89,6,95.7/89.1,47.3/39.8,16.53,-99
219,Uruguay,SouthAmerica,173626,3457,19.8,93.5,53442,1.0,15573.8,6.8,...,64.6,106,10.4,6.7/2.0,113,58,100.0/93.9,96.6/92.6,0.04,-99
173,Saint Vincent and the Grenadines,Caribbean,389,110,281.8,101.7,738,1.6,6739.2,7.5,...,51.8,58,69.2,0.2/1.9,0,29,95.1/95.1,.../...,1.80,-99
104,Japan,EasternAsia,377930,127484,349.7,95.4,4383076,1.2,34628.7,1.2,...,93.3,404,68.5,1214.0/9.6,1114,146,100.0/100.0,100.0/100.0,-99,-99
50,Costa Rica,CentralAmerica,51100,4906,96.1,100.1,52958,3.7,11015.0,5.1,...,59.8,340,53.4,7.8/1.6,110,44,99.6/91.9,95.2/92.3,0.22,-99
206,Trinidad and Tobago,Caribbean,5127,1369,266.9,97.1,25927,0.2,19062.9,0.5,...,69.2,69,45.4,46.3/34.2,1663,607,95.1/95.1,91.5/91.5,...,-99
115,Liberia,WesternAfrica,111369,4732,49.1,101.8,2053,0.3,455.9,70.8,...,5.9,172,43.7,0.9/0.2,73,19,88.6/62.6,28.0/5.9,61.73,-99
77,Georgia,WesternAsia,69700,3912,56.3,91.4,13965,2.8,3491.4,9.0,...,45.2,120,40.6,9.0/2.2,61,47,100.0/100.0,95.2/75.9,3.30,-99
179,Serbia,SouthernEurope,88499,8791,100.5,95.6,37160,0.8,5238.6,8.2,...,65.3,71,31.1,37.7/4.3,393,62,99.4/98.9,98.2/94.2,0.90,-99
82,Greenland,NorthernAmerica,2166086,56,0.1,112.1,2078,0.3,36976.7,10.0,...,67.6,23,~0.0,0.5/9.0,2,154,100.0/100.0,100.0/100.0,-99,-99
57,Denmark,NorthernEurope,42921,5734,135.1,99.0,301308,1.6,53149.3,1.2,...,96.3,47,14.4,33.5/5.9,666,119,100.0/100.0,99.6/99.6,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,25.1,298,1.0,22.7/0.9,668,12,72.0/46.5,92.5/34.1,2.99,-99
65,Eritrea,EasternAfrica,117600,5069,50.2,100.4,4783,4.8,914.9,17.2,...,1.1,122,15.0,0.7/0.1,27,7,73.2/53.3,44.6/7.3,...,-99
88,Guinea,WesternAfrica,245857,12717,51.8,100.6,8875,0.1,703.9,19.8,...,4.7,185,26.0,2.4/0.2,113,12,92.7/67.4,34.1/11.8,8.65,-99
46,Colombia,SouthAmerica,1141748,49066,44.2,96.8,292080,3.1,6056.1,6.8,...,55.9,835,52.8,84.1/1.8,5380,31,96.8/73.8,85.2/67.9,0.47,-99
182,Singapore,South-easternAsia,719,5709,8155.5,97.7,292734,2.0,52239.0,~0.0,...,82.1,293,23.1,56.4/10.2,27,209,100.0/...,100.0/...,-99,-99
84,Guadeloupe,Caribbean,1705,450,266.0,86.4,-99,-99,-99.0,-99,...,-99,73,43.0,2.6/5.5,5,80,99.3/99.8,97.0/89.5,-99,-99
102,Italy,SouthernEurope,302073,59360,201.8,95.1,1821580,0.7,30462.4,2.2,...,65.6,359,31.4,320.4/5.4,1539,103,100.0/100.0,99.5/99.6,-99,-99
139,Myanmar,South-easternAsia,676577,53371,81.7,95.5,62601,7.3,1161.5,26.7,...,21.8,321,45.3,21.6/0.4,1078,15,92.7/74.4,84.3/77.1,2.23,-99
9,Armenia,WesternAsia,29743,2930,102.9,88.8,10529,3.0,3489.1,19.0,...,58.2,114,11.7,5.5/1.8,48,46,100.0/100.0,96.2/78.2,3.17,-99
18,Belarus,EasternEurope,207600,9468,46.7,87.0,54609,-3.9,5750.8,7.5,...,62.2,25,42.5,63.5/6.7,155,122,99.9/99.1,94.1/95.2,0.20,-99
212,Uganda,EasternAfrica,241550,42863,214.5,99.0,25282,5.4,647.7,25.6,...,19.2,196,11.0,5.2/0.1,409,12,95.5/75.8,28.5/17.3,6.35,-99
220,Uzbekistan,CentralAsia,448969,31911,75.0,99.4,69004,6.8,2308.3,19.2,...,42.8,59,7.6,105.2/3.6,2339,62,98.5/80.9,100.0/100.0,0.66,-99
97,Iran (Islamic Republic of),SouthernAsia,1628750,81163,49.8,101.2,398563,0.4,5038.1,8.6,...,44.1,134,6.6,649.5/8.3,13291,127,97.7/92.1,92.8/82.3,0.02,-99
171,Saint Lucia,Caribbean,539,179,293.2,95.9,1450,1.9,7839.4,2.7,...,52.4,62,33.4,0.4/2.2,0,33,99.5/95.6,84.7/91.9,0.97,-99
214,United Arab Emirates,WesternAsia,83600,9400,112.4,262.4,370296,3.8,40438.8,0.7,...,91.2,56,3.8,211.4/23.2,8642,366,99.6/100.0,98.0/95.2,-99,-99

In [19]:
#correlation between GDP per capita and Urban population %
corr = df[['GDP per capita (current US$)','Urban population (% of total population)']].corr(numeric_only = True)
corr

,GDP per capita (current US$),Urban population (% of total population)
GDP per capita (current US$),1.000000,0.396739
Urban population (% of total population),0.396739,1.000000

In [20]:
corr = sample_df[['GDP per capita (current US$)','Urban population (% of total population)']].corr(numeric_only = True)
corr

,GDP per capita (current US$),Urban population (% of total population)
GDP per capita (current US$),1.000000,0.521547
Urban population (% of total population),0.521547,1.000000